export const DATA_JSON = 'DATA_JSON';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_PRICE_RANGE = 'FILTER_BY_PRICE_RANGE';
export const RESET_FILTERS = 'RESET_FILTERS';
export const VIEW_PRODUCT_DETAILS = 'VIEW_PRODUCT_DETAILS';
export const SET_SELECTED_PRODUCT_ID = 'SET_SELECTED_PRODUCT_ID';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const UPDATE_CART_COUNT = 'UPDATE_CART_COUNT';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';



